basePath: /api
definitions:
  model.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.HealthResponse:
    properties:
      success:
        type: boolean
    type: object
  model.Language:
    properties:
      code:
        type: string
      sections:
        items:
          $ref: '#/definitions/model.Section'
        type: array
    type: object
  model.Section:
    properties:
      content_type:
        type: string
      data: {}
      icon:
        type: string
      title:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  title: URFU-Guide
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: check health
      tags:
      - admin
  /v1/sections:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Language'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: check health
      tags:
      - public
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
